//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OperarionError_Delete {
            get {
                return ResourceManager.GetString("OperarionError_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matching file&apos;s last modification date is before than the source file last modification date..
        /// </summary>
        internal static string OperarionError_DestFileBeforeWriteTime {
            get {
                return ResourceManager.GetString("OperarionError_DestFileBeforeWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matching file&apos;s &apos;Directory&apos; attribute is different than the source file&apos;s &apos;Directory&apos; Attribute..
        /// </summary>
        internal static string OperarionError_DestFileDifferentDirAttr {
            get {
                return ResourceManager.GetString("OperarionError_DestFileDifferentDirAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching file was not found in the destination path. Operation may continue..
        /// </summary>
        internal static string OperarionError_DestFileDoesNotExists {
            get {
                return ResourceManager.GetString("OperarionError_DestFileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matching file&apos;s last modification date is later than the source file last modification date..
        /// </summary>
        internal static string OperarionError_DestFileLaterLastWriteTime {
            get {
                return ResourceManager.GetString("OperarionError_DestFileLaterLastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matching file&apos;s last modification date is the same as source file last modification date, however it&apos;s length is different..
        /// </summary>
        internal static string OperarionError_DestFileSameWriteTimeDifferentLength {
            get {
                return ResourceManager.GetString("OperarionError_DestFileSameWriteTimeDifferentLength", resourceCulture);
            }
        }
    }
}
